name: minibook-backend

services:
  - name: api
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: UMGC-Capstone-Project/minibook-backend
    build_command: npm run build
    run_command: npm run start:prod
    http_port: 3000
    envs:
      - key: API_URL
        value: https://api.minibook.io/
      - key: DATABASE_HOST
        value: 
      - key: DATABASE_PORT
        value: 
      - key: DATABASE_USERNAME
        value: 
      - key: DATABASE_PASSWORD
        value: 
      - key: DATABASE_CA_CERT
        value: 
      - key: DB_SYNCHRONIZE
        value: true
    routes:
      - path: /
    health_check:
      http_path: /status
    cors:
      allow_origins:
        - regex: .*